- id: doi:10.1002/1873-3468.14067
  image: https://febs.onlinelibrary.wiley.com/cms/asset/4a3a1cde-1265-471c-87af-f7556d28db36/feb213824-toc-0001-m.jpg
  date: 2021-4-11
  tags:
    - open science

- id: arxiv:2104.11364v1
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  date: 2021-4-23
  tags:
    - open science

- id: doi:10.1091/mbc.E20-12-0784
  image: https://www.molbiolcell.org/cms/10.1091/mbc.E20-12-0784/asset/images/medium/mbc-32-995-g001.gif
  repo: broadinstitute/cell-health
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2020.07.08.193938v2
    - type: source
      link: https://github.com/broadinstitute/cell-health
      text: Analysis
  tags:
    - image-based profiling
    - cell biology

- id: doi:10.1186/s13059-020-02021-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-020-02021-3/MediaObjects/13059_2020_2021_Fig6_HTML.png?as=webp
  repo: greenelab/biobombe
  extra-links:
    - type: preprint
      link: https://doi.org/10.1101/573782
    - type: source
      link: https://github.com/greenelab/biobombe
      text: Analysis
    - type: data
      link: https://greenelab.github.io/BioBombe/
      text: Embeddings
  tags:
    - biological representations
    - unsupervised learning
    - autoencoder
    - cancer 
