- id: doi:10.1002/1873-3468.14067
  image: https://febs.onlinelibrary.wiley.com/cms/asset/4a3a1cde-1265-471c-87af-f7556d28db36/feb213824-toc-0001-m.jpg
  date: 2021-4-11
  tags:
    - open science

- id: arxiv:2104.11364v1
  authors:
    - Anne E Carpenter
    - Casey S Greene
    - Piero Carnici
    - Benilton S Carvalho
    - Michiel de Hoon
    - Stacey Finley
    - Kim-Anh Le Cao
    - Jerry SH Lee
    - Luigi Marchionni
    - Suzanne Sindi
    - Fabian J Theis
    - Gregory P Way
    - Jean YH Yang
    - Elana J Fertig
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Fish_farming_Martinniemi_Oulu_20200713_01.jpg/1599px-Fish_farming_Martinniemi_Oulu_20200713_01.jpg
  date: 2021-4-23
  tags:
    - open science

- id: doi:10.1091/mbc.E20-12-0784
  image: https://www.molbiolcell.org/cms/10.1091/mbc.E20-12-0784/asset/images/medium/mbc-32-995-g001.gif
  repo: broadinstitute/cell-health
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2020.07.08.193938v2
    - type: source
      link: https://github.com/broadinstitute/cell-health
      text: Analysis
  tags:
    - image-based profiling
    - cell biology

- id: doi:10.1186/s13059-020-02021-3
  image: https://raw.githubusercontent.com/greenelab/BioBombe/master/docs/favicon-192x192.png
  repo: greenelab/biobombe
  extra-links:
    - type: preprint
      link: https://doi.org/10.1101/573782
    - type: source
      link: https://github.com/greenelab/biobombe
      text: Analysis
    - type: data
      link: https://greenelab.github.io/BioBombe/
      text: Embeddings
  tags:
    - biological representations
    - unsupervised learning
    - cancer
