- id: doi:10.1002/1873-3468.14067
  image: https://febs.onlinelibrary.wiley.com/cms/asset/4a3a1cde-1265-471c-87af-f7556d28db36/feb213824-toc-0001-m.jpg
  date: 2021-4-11
  tags:
    - open science

- id: arxiv:2104.11364v1
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  date: 2021-4-23
  tags:
    - open science

- id: doi:10.1091/mbc.E20-12-0784
  image: https://www.molbiolcell.org/cms/10.1091/mbc.E20-12-0784/asset/images/medium/mbc-32-995-g001.gif
  repo: broadinstitute/cell-health
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2020.07.08.193938v2
    - type: source
      link: https://github.com/broadinstitute/cell-health
      text: Analysis source
  tags:
    - image-based profiling
    - cell biology
